# Generated by Django 5.0.6 on 2024-07-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('nida_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pupil_pictures/')),
                ('current_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='studentapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('nida_id', models.CharField(max_length=20, unique=True)),
                ('relationship', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='guardian_pictures/')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.class')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.pupil')),
            ],
        ),
    ]
